name: "scalified/cleanup-action"
description: "Cleans up the workspace and user-defined paths"
author: "Scalified"
branding:
  icon: "box"
  color: "gray-dark"

inputs:
  paths:
    description: "List of files and directories to remove"
    required: false
    default: ""
  docker-image:
    description: "Docker image to remove"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - id: cleanup
      name: "Cleanup"
      env:
        INPUT_PATHS: ${{ inputs.paths }}
        INPUT_DOCKER_IMAGE: ${{ inputs.docker-image }}
      run: |
        # Cleanup '${{ github.workspace }}' workspace
        echo "::group::🧹 Cleaning up '${{ github.workspace }}' workspace"
        rm -rf ${{ github.workspace }}/{*,.[!.]*,..?*}
        echo "✅ Workspace '${{ github.workspace }}' has been cleaned"
        echo "::endgroup::"

        if [ -n "$INPUT_PATHS" ]; then
          echo "::group::🧹 Cleaning up user-defined paths"
          read -ra PATHS <<< "$INPUT_PATHS"
          for path in "${PATHS[@]}"; do
            rm -rf "$path"
            echo "✅ Removed '$path' path"
          done
          echo "::endgroup::"
        fi
        
        if [ -n "$INPUT_DOCKER_IMAGE" ]; then
          echo "::group::🧹 Removing Docker containers and '$INPUT_DOCKER_IMAGE' image"
          CONTAINERS=$(docker ps -a -q --filter "ancestor=$INPUT_DOCKER_IMAGE")
          if [ -n "$CONTAINERS" ]; then
            docker rm -f $CONTAINERS
            echo "✅ Removed containers using '$INPUT_DOCKER_IMAGE' image"
          fi
          docker rmi -f $INPUT_DOCKER_IMAGE
          echo "✅ Removed Docker '$INPUT_DOCKER_IMAGE' image"
          echo "::endgroup::"
        fi
      shell: bash
